#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH -p mhigh # Partition to submit to
#SBATCH -q masterhigh # Required to requeue other users mlow queue jobs
#SBATCH --mem 8192 # 8GB memory
#SBATCH --gres gpu:1 # Request of 1 gpu
#SBATCH -o logs/%x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e logs/%x_%u_%j.err # File to which STDERR will be written
python main.py --zoo-model "Cityscapes/mask_rcnn_R_50_FPN.yaml" --do-task-a --task-a-configuration "configuration_2" --zoo-model-name "Cityscapes" --model-name "Task-a-conf2-NO-DA" --lr 0.00025 --iterations 5000 --th 0.8
